export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const SETUP_NFL_DRAFTROOM = 'SETUP_NFL_DRAFTROOM';
export const SETUP_FANTASY_DRAFTROOM = 'SETUP_FANTASY_DRAFTROOM';
export const TOGGLE_PLAYERS_MODAL = 'TOGGLE_PLAYERS_MODAL';
